# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=50)),
                ('p_nombre', models.CharField(max_length=40)),
                ('s_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('p_apellido', models.CharField(max_length=40)),
                ('s_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('esta_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=50)),
                ('nivel_instruc', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachiller', 'Bachiller'), ('Universitario', 'Universitario')], max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('cargo', models.CharField(blank=True, choices=[('Secretaria', 'Secretaria'), ('Jefe de Departamento', 'Jefe de Departamento'), ('Solicitante', 'Solicitante')], default='Solicitante', max_length=50, null=True)),
                ('trabaja', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50)),
                ('inscrito', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50)),
                ('registro', models.CharField(choices=[('G.M.V.V', 'G.M.V.V'), ('0800 Mi Hogar', '0800 Mi Hogar')], max_length=50)),
                ('pareja', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=50)),
                ('ingre_mensual', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
